server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: app-server-fileStore
  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 200MB # 单个文件大小
      max-request-size: 1024MB # 设置总上传的文件大小
# minio配置
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  domain: https://file.liming.top

logging:
  level:
    ROOT: INFO
    com.minio: DEBUG
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{50} - %msg%n'
  file:
    name: ${logging.file.path}/${spring.application.name}.log
    path: /home/logs/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

